from pydantic import BaseModel
class InputData(BaseModel):
    CNT_CHILDREN: float
    AMT_INCOME_TOTAL: float
    AMT_CREDIT: float
    AMT_ANNUITY: float
    NAME_TYPE_SUITE: float
    NAME_INCOME_TYPE: float
    NAME_EDUCATION_TYPE: float
    NAME_FAMILY_STATUS: float
    NAME_HOUSING_TYPE: float
    REGION_POPULATION_RELATIVE: float
    DAYS_BIRTH: float
    DAYS_EMPLOYED: float
    DAYS_REGISTRATION: float
    OWN_CAR_AGE: float
    FLAG_WORK_PHONE: float
    FLAG_CONT_MOBILE: float
    FLAG_PHONE: float
    FLAG_EMAIL: float
    OCCUPATION_TYPE: float
    CNT_FAM_MEMBERS: float
    REGION_RATING_CLIENT: float
    WEEKDAY_APPR_PROCESS_START: float
    HOUR_APPR_PROCESS_START: float
    LIVE_REGION_NOT_WORK_REGION: float
    REG_CITY_NOT_LIVE_CITY: float
    REG_CITY_NOT_WORK_CITY: float
    LIVE_CITY_NOT_WORK_CITY: float
    ORGANIZATION_TYPE: float
    EXT_SOURCE_1: float
    EXT_SOURCE_2: float
    EXT_SOURCE_3: float
    APARTMENTS_AVG: float
    BASEMENTAREA_AVG: float
    YEARS_BEGINEXPLUATATION_AVG: float
    YEARS_BUILD_AVG: float
    COMMONAREA_AVG: float
    ELEVATORS_AVG: float
    ENTRANCES_AVG: float
    FLOORSMAX_AVG: float
    FLOORSMIN_AVG: float
    LANDAREA_AVG: float
    LIVINGAPARTMENTS_AVG: float
    LIVINGAREA_AVG: float
    NONLIVINGAPARTMENTS_AVG: float
    NONLIVINGAREA_AVG: float
    FONDKAPREMONT_MODE: float
    HOUSETYPE_MODE: float
    WALLSMATERIAL_MODE: float
    OBS_30_CNT_SOCIAL_CIRCLE: float
    DEF_30_CNT_SOCIAL_CIRCLE: float
    DEF_60_CNT_SOCIAL_CIRCLE: float
    DAYS_LAST_PHONE_CHANGE: float
    FLAG_DOCUMENT_3: float
    FLAG_DOCUMENT_5: float
    FLAG_DOCUMENT_6: float
    FLAG_DOCUMENT_8: float
    FLAG_DOCUMENT_11: float
    FLAG_DOCUMENT_18: float
    AMT_REQ_CREDIT_BUREAU_WEEK: float
    AMT_REQ_CREDIT_BUREAU_MON: float
    AMT_REQ_CREDIT_BUREAU_QRT: float
    AMT_REQ_CREDIT_BUREAU_YEAR: float
    OWN_CAR_AGE_na: float
    EXT_SOURCE_1_na: float
    EXT_SOURCE_2_na: float
    EXT_SOURCE_3_na: float
    BASEMENTAREA_AVG_na: float
    LANDAREA_AVG_na: float
    OCCUPATION_TYPE_na: float
    AMT_CREDIT_SUM_sum: float
    AMT_CREDIT_SUM_mean: float
    AMT_CREDIT_SUM_max: float
    AMT_CREDIT_SUM_min: float
    AMT_CREDIT_SUM_DEBT_sum: float
    AMT_CREDIT_SUM_DEBT_mean: float
    AMT_CREDIT_SUM_DEBT_min: float
    AMT_CREDIT_SUM_LIMIT_sum: float
    AMT_CREDIT_SUM_LIMIT_mean: float
    AMT_CREDIT_SUM_LIMIT_min: float
    AMT_ANNUITY_sum_x: float
    AMT_ANNUITY_mean_x: float
    AMT_ANNUITY_min_x: float
    AMT_CREDIT_MAX_OVERDUE_sum: float
    CREDIT_DAY_OVERDUE_sum: float
    CREDIT_DAY_OVERDUE_mean: float
    CNT_CREDIT_PROLONG_sum: float
    CNT_CREDIT_PROLONG_mean: float
    DAYS_CREDIT_min: float
    DAYS_CREDIT_max: float
    DAYS_CREDIT_mean: float
    DAYS_CREDIT_ENDDATE_min: float
    DAYS_CREDIT_ENDDATE_max: float
    DAYS_CREDIT_ENDDATE_mean: float
    DAYS_ENDDATE_FACT_min: float
    DAYS_ENDDATE_FACT_max: float
    DAYS_ENDDATE_FACT_mean: float
    DAYS_CREDIT_UPDATE_min: float
    DAYS_CREDIT_UPDATE_max: float
    DAYS_CREDIT_UPDATE_mean: float
    months_balance_min_min: float
    months_balance_max_max: float
    status_0_sum_sum: float
    status_1_sum_sum: float
    status_2_sum_sum: float
    status_5_sum_sum: float
    status_C_sum_sum: float
    status_X_sum_sum: float
    credit_active_Active_sum: float
    credit_active_Closed_sum: float
    credit_active_Sold_sum: float
    AMT_ANNUITY_sum_y: float
    AMT_ANNUITY_mean_y: float
    AMT_ANNUITY_max_y: float
    AMT_ANNUITY_min_y: float
    AMT_APPLICATION_mean: float
    AMT_APPLICATION_max: float
    AMT_APPLICATION_min: float
    AMT_DOWN_PAYMENT_sum: float
    AMT_DOWN_PAYMENT_mean: float
    AMT_DOWN_PAYMENT_min: float
    AMT_GOODS_PRICE_min: float
    DAYS_DECISION_min: float
    DAYS_DECISION_max: float
    DAYS_DECISION_mean: float
    DAYS_FIRST_DRAWING_min: float
    DAYS_FIRST_DRAWING_mean: float
    DAYS_FIRST_DUE_min: float
    DAYS_FIRST_DUE_max: float
    DAYS_FIRST_DUE_mean: float
    DAYS_LAST_DUE_min: float
    DAYS_LAST_DUE_max: float
    DAYS_LAST_DUE_mean: float
    NAME_CONTRACT_TYPE_Consumer_loans_sum: float
    NAME_CONTRACT_TYPE_Revolving_loans_sum: float
    NAME_CONTRACT_STATUS_Canceled_sum: float
    NAME_CONTRACT_STATUS_Refused_sum: float
    NAME_CONTRACT_STATUS_Unused_offer_sum: float
    MONTHS_BALANCE_max_x: float
    CNT_INSTALMENT_sum: float
    CNT_INSTALMENT_mean: float
    CNT_INSTALMENT_max: float
    CNT_INSTALMENT_min: float
    CNT_INSTALMENT_FUTURE_min: float
    SK_DPD_sum_x: float
    SK_DPD_DEF_sum_x: float
    pos_status_Active_sum: float
    pos_status_Completed_sum: float
    pos_status_Demand_sum: float
    pos_status_Returned_to_the_store_sum: float
    pos_status_Signed_sum: float
    MONTHS_BALANCE_min_y: float
    MONTHS_BALANCE_max_y: float
    AMT_BALANCE_sum: float
    AMT_BALANCE_mean: float
    AMT_BALANCE_min: float
    AMT_CREDIT_LIMIT_ACTUAL_sum: float
    AMT_CREDIT_LIMIT_ACTUAL_mean: float
    AMT_DRAWINGS_ATM_CURRENT_sum: float
    AMT_DRAWINGS_ATM_CURRENT_mean: float
    AMT_DRAWINGS_ATM_CURRENT_max: float
    AMT_DRAWINGS_CURRENT_sum: float
    AMT_DRAWINGS_CURRENT_mean: float
    AMT_DRAWINGS_CURRENT_max: float
    AMT_DRAWINGS_CURRENT_min: float
    AMT_DRAWINGS_OTHER_CURRENT_sum: float
    AMT_DRAWINGS_OTHER_CURRENT_mean: float
    AMT_DRAWINGS_OTHER_CURRENT_max: float
    AMT_DRAWINGS_POS_CURRENT_sum: float
    AMT_DRAWINGS_POS_CURRENT_mean: float
    AMT_DRAWINGS_POS_CURRENT_max: float
    AMT_DRAWINGS_POS_CURRENT_min: float
    AMT_INST_MIN_REGULARITY_min: float
    AMT_PAYMENT_CURRENT_mean: float
    AMT_PAYMENT_CURRENT_max: float
    AMT_PAYMENT_CURRENT_min: float
    AMT_PAYMENT_TOTAL_CURRENT_min: float
    CNT_DRAWINGS_ATM_CURRENT_sum: float
    CNT_DRAWINGS_ATM_CURRENT_mean: float
    CNT_DRAWINGS_ATM_CURRENT_max: float
    CNT_DRAWINGS_ATM_CURRENT_min: float
    CNT_DRAWINGS_CURRENT_sum: float
    CNT_DRAWINGS_CURRENT_mean: float
    CNT_DRAWINGS_CURRENT_max: float
    CNT_DRAWINGS_CURRENT_min: float
    CNT_DRAWINGS_OTHER_CURRENT_sum: float
    CNT_DRAWINGS_OTHER_CURRENT_mean: float
    CNT_DRAWINGS_OTHER_CURRENT_max: float
    CNT_DRAWINGS_POS_CURRENT_min: float
    CNT_INSTALMENT_MATURE_CUM_sum: float
    CNT_INSTALMENT_MATURE_CUM_min: float
    cc_status_Completed_sum: float
    cc_status_Sent_proposal_sum: float
    SK_DPD_sum_y: float
    SK_DPD_DEF_sum_y: float
    DAYS_INSTALMENT_max: float
    DAYS_INSTALMENT_mean: float
    AMT_INSTALMENT_sum: float
    AMT_INSTALMENT_mean: float
    AMT_INSTALMENT_max: float
    AMT_INSTALMENT_min: float
    AMT_CREDIT_SUM_DEBT_mean_na: float
    AMT_CREDIT_SUM_LIMIT_mean_na: float
    AMT_ANNUITY_mean_x_na: float
    AMT_CREDIT_MAX_OVERDUE_mean_na: float
    months_balance_min_min_na: float
    AMT_DOWN_PAYMENT_mean_na: float
    NAME_CONTRACT_TYPE_Cash_loans: float
    CODE_GENDER_F: float
    CODE_GENDER_M: float
    FLAG_OWN_CAR_N: float
    FLAG_OWN_REALTY_N: float
    EMERGENCYSTATE_MODE_Unknown: float